# Copyright 2026 作者：灵犀
# 应用描述生成任务配置

# 基本参数
input_file: "/home/ma-user/work/dataset/game_gr_data_jw/game_item_info/test/input1_add_desc_and_comment_short.csv"
output_file: "/home/ma-user/work/dataset/game_gr_data_jw/game_item_info/test/input1_add_desc_and_comment_llm.csv"
model_path: "/home/ma-user/work/dataset/qwen3_4b_instruct_weights_jw"
aggregate: true

task:
  name: "app_desc"
  input_column: "app_cn_name"
  output_column: "llm_desc"
  primary_key: "app_id"
  valid_condition: "not_empty"  # not_empty, all

# 预处理函数链（按顺序执行）
preprocessors: [ ]

# 生成参数
generation:
  max_new_tokens: 512
  temperature: 0.7
  top_p: 0.9
  do_sample: true
  max_length: 8192
  log_every_n_steps: 10

# 后处理函数链（按顺序执行）
postprocessors:
  - name: "replace_empty"
    params:
      keywords:
        - "EMPTY_CONTENT"
        - "EMPTY"
        - "CONTENT"

# Prompt配置文件路径
system_prompt_file: "prompts/app_desc/base.txt"
user_prompt_file: "prompts/app_desc/user.txt"
